### ISSUE TITLE
Site-wide settings related to payment

### ISSUE THREAD

**Issue by diane-villemure** [lmsdoctor/moodle-enrol_payment#3]
When PayPal and/or Stripe are configured and "Allow Payment enrolments" is set to "No", that setting makes no difference. Both the PayPal and/or Stripe buttons are active. I was able to enrol a student using Stripe. I was also able to create a new Payment enrolment method in a course (which I'm thinking that if the "Enrolment instance defaults" setting "Allow Payment enrolments" is set to "No", the teacher or course creator should not have that option in the Users -> Enrolment methods -> "Add method" drop down menu.

When PayPal is not configured (i.e., there is no entry in the "PayPal business email") but Stripe is configured, the PayPal button doesn't display but the "OR" language string appears above the Stripe button. Is it possible to wrap the "OR" string in an if condition?

**Comment by lmsdoctor** [comment]
If the setting "Allow Payment Enrolments" is set to "No", I disable the payments for all instances showing this message: https://prnt.sc/r5h14t ... But unfortunately I cannot restrict adding the payment method in the courses. The only way that can happen is if the plugin payment is disabled from Enrollment methods from the site administrator.
